#!/bin/sh

if git-rev-parse --verify HEAD >/dev/null 2>&1 ; then
   against=HEAD
else
   # Initial commit: diff against an empty tree object
   against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

changed_source_files=`git diff --name-only $against `

if [ -n "$changed_source_files" ]; then
    found_offenses=''

    for file in $changed_source_files ; do
        too_long=`git diff-index --cached -p $against -- "$file" |
                  egrep '^\+.{80,}' |
                  sed -E 's/^\+//'`
        
        if [ -n "$too_long" ]; then
            found_offenses='YES'
            printf "\n$file:\n%s\n" "$too_long" >&2
        fi
    done
 
    if [ $found_offenses = 'YES' ]; then
        echo "\nAborting commit because you added lines longer than 80 chars." >&2
        exit 1
    fi
fi 
